- auth.ts
If user is not logged in (has a session), it will be redirected to the signin page.
Resolves https://github.com/Vasteras-Stadsmission/matkassen-issues/issues/22
> Restrict access to any page unless logged in

- README.md
- deploy.sh
This contains the IP to the server and info on how to SSH there. Updated some parts of the deploy.sh script, but need to do more there.
> Add initial deployment information

- .github/workflows/deploy.yml
- deploy.sh
As a step towards being able to deploy to VPS
Relates to https://github.com/Vasteras-Stadsmission/matkassen-issues/issues/20
> Add deploy GitHub Action and update deploy.sh script

- bun.lock
- package.json
The deployment failed due to missing packages.
> Add missing packages

- .github/workflows/init_deploy.yml
The syntax was incorrect. Now it should only trigger manually, and only from main.
> Fix init deploy script

- .github/workflows/init_deploy.yml
- README.md
- deploy.sh
- docker-compose.yml
- Remove unnecessary content from README since it is already part of deploy.sh
- In deploy-sh add:
- SSL Certificate Auto-renewal
- Environment Variables Validation
- Disable Default Nginx Site (which could cause conflicts)
- Docker Restart Policy: ensure Docker containers restart automatically after server reboots
- Instead of having a hardcoded name 'myapp', use a specific PROJECT_NAME variable
- Remove automatic cron job to delete database content
- replace deprecated apt-key with new keyring method
- Add certbot for www.DOMAIN as well
- only add swap file if it does not exist
- Add docker image cleanup
- Add additional security headers for nginx
- Update to syntax recommended for Docker Compose V2
> Improve the initial deploy.sh script

- Dockerfile
- deploy.sh
- `AUTH_URL` is not necessarily needed, but added just in case
- `AUTH_TRUST_HOST` is needed for reverse proxy (nginx)
- Dockerfile updates are necessary according to documentation
> Add missing auth.js config needed for prod

- bun.lock
> Update bun.lock file

- .github/workflows/codeql.yml
It was too annoying having it run on each PR.
> Run CodeQL only on cron

- .github/workflows/init_deploy.yml
- deploy.sh
- Includes nginx and certs fixes
> Add possibility to fully deploy to staging

- deploy.sh
See https://github.com/nextauthjs/next-auth/issues/9819\#issuecomment-1912903196
> Remove AUTH_URL to mitigate errors

- auth.ts
- deploy.sh
- middleware.ts
Middleware handles exceptions: black list and white list
> Restrict access by default unless logged in

- .github/workflows/build.yml
- .github/workflows/continuous_deployment.yml
- .github/workflows/deploy.yml
- deploy.sh
Previously, the env variables would not be updated on CD - only on init deploy.
> Update env variables in continuous deployment

- .env.example
- .github/workflows/build.yml
- .github/workflows/continuous_deployment.yml
- .github/workflows/init_deploy.yml
- .gitignore
- .prettierignore
- README.md
- deploy.sh
- docker-compose.dev.yml
- docker-compose.yml
- drizzle.config.ts
- migrations/0000_fancy_brood.sql
- migrations/meta/0000_snapshot.json
- migrations/meta/_journal.json
- package.json
- scripts/wait-for-db.sh
- update.sh
This is because schema > DB caused issues in CI becuase it is generating prompts.
Instead we opt for the intermediate SQL migration script generation and apply them instead.
> Move from [schema > db] to [schema > SQL migration files > DB]

- .github/workflows/continuous_deployment.yml
- .github/workflows/init_deploy.yml
- Dockerfile
- migration files were not copied to the docker container, and thus they could not be executed on the target VPS
- github actions were not correctly verifying that db migrations were successful
> Fix database migration issues

- app/db/actions.ts
- app/db/page.tsx
- app/db/schema.ts
- migrations/0001_wandering_punisher.sql
- migrations/meta/0001_snapshot.json
- migrations/meta/_journal.json
Contains households and the different dependencies.
> Add first matkassen DB schema draft

- app/client-providers.tsx
- app/households/[id]/edit/client.tsx
- app/households/enroll/components/FoodParcelsForm.tsx
- app/households/enroll/components/HouseholdForm.tsx
- app/households/enroll/components/ReviewForm.tsx
- app/households/enroll/page.tsx
- app/households/page.tsx
- app/layout.tsx
- bun.lock
- components/household-wizard/HouseholdWizard.tsx
- package.json
- Integrate @mantine/notifications for toast messages after household operations
- Implement query parameter-based success notifications on redirect
- Improve form validation and error handling across components
- Add bulk time editing feature to FoodParcelsForm component
- Enhance error handling in form submission flows
- Fix duplicate submit button in ReviewForm
> Add notifications system and enhance form usability

- .env.example
- app/db/schema.ts
- app/households/[id]/edit/actions.ts
- app/households/[id]/edit/client.tsx
- app/households/actions.ts
- app/households/components/CommentHtml.module.css
- app/households/components/CommentHtml.tsx
- app/households/components/HouseholdComments.tsx
- app/households/components/HouseholdDetail.tsx
- app/households/components/HouseholdsTable.tsx
- app/households/enroll/actions.ts
- app/households/enroll/components/ReviewForm.tsx
- app/households/enroll/types.ts
- bun.lock
- components/household-wizard/HouseholdWizard.tsx
- migrations/0006_needy_tusk.sql
- migrations/0007_special_nicolaos.sql
- migrations/meta/0006_snapshot.json
- migrations/meta/0007_snapshot.json
- migrations/meta/_journal.json
- package.json
- Add GitHub user integration for comment authorship
- Create new comments UI components with HTML support
- Integrate comments in household detail, edit, and enrollment views
- Update database schema with author_github_username field
- Add migration scripts for database changes
- Improve UI layout for comments display
- Fix circular dependency issues in types
- Add GitHub API token support in .env.example
- Implement cached GitHub user data fetching using React's cache function
- Create reusable functions for fetching single and multiple GitHub user profiles
- Enhance comments with GitHub user avatars and names
- Optimize comment display by fetching user data server-side
- Remove client-side GitHub API calls in CommentHtml component
- Update Comment interface to make id, created_at and …
> Add household comments functionality

- .github/workflows/build.yml
- __tests__/app/schedule/components/TimeSlotCell.test.tsx
- __tests__/app/schedule/components/WeeklyScheduleGrid.test.tsx
- __tests__/app/schedule/utils/date-utils.test.ts
- __tests__/app/schedule/utils/schedule-utils.test.ts
- app/db/drizzle.ts
- app/households/[id]/edit/client.tsx
- app/households/enroll/page.tsx
- app/schedule/actions.ts
- app/schedule/components/PickupCard.tsx
- app/schedule/components/TimeSlotCell.tsx
- app/schedule/components/WeeklyScheduleGrid.tsx
- app/schedule/page.tsx
- app/utils/date-utils.ts
- bun.lock
- package.json
- types/bun-test.d.ts
- types/happy-dom.d.ts
The weekly schedule page has drag and drop functionality.
Unit tests were added, as well as the unit test framework. Now running unit tests is a part of the CI build pipeline.
> Add weekly schedule page and unit test

- .eslintrc.json
- app/[locale]/auth/signin/SignInClient.tsx
- app/[locale]/auth/signin/page.tsx
- app/[locale]/households/[id]/edit/page.tsx
- app/[locale]/layout.tsx
- components/AuthDropdown/AuthDropdown.module.css
- components/AuthDropdown/AuthDropdown.tsx
- components/HeaderSimple/HeaderSimple.tsx
- messages/en.json
- messages/sv.json
- middleware.ts
Remove unecessary stuff and make it look more modern with username etc under the avatar. This is to avoid bloating the nav bar.
> Make auth pretty

- __tests__/app/api/csp-report/route.test.ts
- app/[locale]/auth/error/ErrorContent.tsx
- app/api/csp-report/route.ts
- app/db/actions.ts
- app/db/schema.ts
- deploy.sh
- migrations/0012_large_joshua_kane.sql
- migrations/meta/0012_snapshot.json
- migrations/meta/_journal.json
🛡️ Better XSS protection without unsafe-inline scripts ⚡ Improved performance with HTTP/2 and gzip
📊 Security monitoring via CSP violation reports
🔒 Stronger frame protection prevents clickjacking
💾 Smart caching balances performance with data freshness
> Improve XSS protection, gzip performance, monitoring etc.

- deploy.sh
It would previously expect 200, 301 or 302 - but since we use auth you get redirected to 307 and thus it would generate a false warning.
> fix: Allow HTTP 307 when checking if main website URL responds

- app/favicon.ico/route.ts
- deploy.sh
Simplify the nginx config in hopes it will work better.
> Rethink nginx config to avoid chunk errors

- .github/workflows/build.yml
- deploy.sh
- docker-compose.yml
- nginx/README.md
- nginx/generate-nginx-config.sh
- nginx/nginx.conf.template
- nginx/shared.conf
- nginx/validate-config.sh
- systemd/README.md
- systemd/nginx-override.conf
- test-resilience.sh
- update.sh
- Add systemd override for nginx auto-restart on failure with rate limiting
- Implement port conflict detection and resolution in deploy.sh
- Add nginx upstream health checks with failover (max_fails=3, fail_timeout=30s)
- Add /nginx-health endpoint for monitoring and load balancer health checks
- Enhance proxy timeout and retry logic for better error handling
- Add nginx configuration validation before applying changes
- Improve Docker security by binding to localhost only (127.0.0.1:3000:3000)
- Add graceful nginx reload with fallback to restart
- Include comprehensive error handling and logging throughout deployment
- Update update.sh to include resilience features for existing deployments
- Add documentation for all nginx resilience features and troubleshooting
Fixes nginx "address …
> feat: add comprehensive nginx resilience and auto-recovery

- .github/workflows/continuous_deployment.yml
- .github/workflows/init_deploy.yml
- docker-compose.yml
Keep test mode ON for both staging and prod.
> Add HelloSMS credentials to staging and prod

- app/api/admin/sms/parcel/[parcelId]/route.ts
- app/utils/sms/hello-sms.ts
Make sure we actually take in and act on HELLO_SMS_TEST_MODE env var
> Disable HelloSMS in prod

- .github/copilot-instructions.md
- README.md
- deploy.sh
- docker-compose.yml
- update.sh
Augment README.md to explain how env variables should be handled
> Enable SMS test mode in production
